import { Router, type IRouter } from "express";
import healthRouter from "./health";
import analysisRouter from "./analysis";
import preferencesRouter from "./preferences";
import githubRouter from "./github";
import publicRouter from "./public";
import repoFinisherRunsRouter from "./repo-finisher-runs";
import agenticFinisherRouter from "./agentic-finisher";
import asyncJobsRouter from "./async-jobs";
import portfolioFinisherRouter from "./portfolio-finisher";
import selfHealingCiRouter from "./self-healing-ci";
import valuationRouter from "./valuation";
import investmentIntelligenceRouter from "./investment-intelligence";
import portfolioIntelligenceRouter from "./portfolio-intelligence";
import portfolioValuationV2Router from "./portfolio-valuation-v2";
import tieredIntelligenceRouter from "./tiered-intelligence";
import vibeToolsRouter from "./vibe-tools";
import observabilityRouter from "./observability";
import portfolioGraphRouter from "./portfolio-graph";
import assuranceRouter from "./assurance";
import learningAuditRouter from "./learning-audit";
import continuousReposRouter from "./continuous-repos";
import externalCompletionPromptsRouter from "./external-completion-prompts";

const router: IRouter = Router();

router.use(healthRouter);
router.use(analysisRouter);
router.use(preferencesRouter);
router.use(githubRouter);
router.use(publicRouter);
router.use(repoFinisherRunsRouter);
router.use(agenticFinisherRouter);
router.use(asyncJobsRouter);
router.use(portfolioFinisherRouter);
router.use(selfHealingCiRouter);
router.use(portfolioGraphRouter);
router.use(assuranceRouter);
router.use(learningAuditRouter);
router.use(continuousReposRouter);
router.use(externalCompletionPromptsRouter);
router.use(valuationRouter);
router.use(tieredIntelligenceRouter);
router.use(portfolioIntelligenceRouter);
router.use(portfolioValuationV2Router);
router.use(investmentIntelligenceRouter);
router.use(vibeToolsRouter);
router.use(observabilityRouter);

export default router;
